// Auto-generated embedded web files
// Do not edit manually

static const char *html_index = 
    "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>ESP-NODE-2RDM Controller</title>\n"
        "    <style>\n"
        "/* === CSS EMBEDDED === */\n"
        "* {\n"
        "    margin: 0;\n"
        "    padding: 0;\n"
        "    box-sizing: border-box;\n"
        "}\n"
        "\n"
        ":root {\n"
        "    --bg-primary: #0f172a;\n"
        "    --bg-secondary: #1e293b;\n"
        "    --bg-tertiary: #334155;\n"
        "    --bg-card: #1e293b;\n"
        "    --border-color: #334155;\n"
        "    --text-primary: #f1f5f9;\n"
        "    --text-secondary: #94a3b8;\n"
        "    --text-muted: #64748b;\n"
        "    --accent-primary: #3b82f6;\n"
        "    --accent-hover: #2563eb;\n"
        "    --success: #10b981;\n"
        "    --warning: #f59e0b;\n"
        "    --danger: #ef4444;\n"
        "    --info: #06b6d4;\n"
        "}\n"
        "\n"
        "body {\n"
        "    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;\n"
        "    background: var(--bg-primary);\n"
        "    color: var(--text-primary);\n"
        "    line-height: 1.6;\n"
        "    overflow-x: hidden;\n"
        "}\n"
        "\n"
        ".app {\n"
        "    min-height: 100vh;\n"
        "    display: flex;\n"
        "    flex-direction: column;\n"
        "}\n"
        "\n"
        "/* Header */\n"
        ".header {\n"
        "    background: var(--bg-secondary);\n"
        "    border-bottom: 1px solid var(--border-color);\n"
        "    padding: 1rem 2rem;\n"
        "}\n"
        "\n"
        ".header-content {\n"
        "    max-width: 1400px;\n"
        "    margin: 0 auto;\n"
        "    display: flex;\n"
        "    justify-content: space-between;\n"
        "    align-items: center;\n"
        "    flex-wrap: wrap;\n"
        "    gap: 1rem;\n"
        "}\n"
        "\n"
        ".header h1 {\n"
        "    font-size: 1.5rem;\n"
        "    display: flex;\n"
        "    align-items: center;\n"
        "    gap: 0.5rem;\n"
        "}\n"
        "\n"
        ".logo {\n"
        "    width: 2rem;\n"
        "    height: 2rem;\n"
        "    color: var(--accent-primary);\n"
        "}\n"
        "\n"
        ".connection-status {\n"
        "    display: flex;\n"
        "    align-items: center;\n"
        "    gap: 0.5rem;\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        ".status-indicator {\n"
        "    width: 0.75rem;\n"
        "    height: 0.75rem;\n"
        "    border-radius: 50%;\n"
        "    background: var(--text-muted);\n"
        "    animation: pulse 2s infinite;\n"
        "}\n"
        "\n"
        ".status-indicator.connected {\n"
        "    background: var(--success);\n"
        "}\n"
        "\n"
        ".status-indicator.disconnected {\n"
        "    background: var(--danger);\n"
        "    animation: none;\n"
        "}\n"
        "\n"
        "@keyframes pulse {\n"
        "    0%, 100% { opacity: 1; }\n"
        "    50% { opacity: 0.5; }\n"
        "}\n"
        "\n"
        "/* Tabs Navigation */\n"
        ".tabs {\n"
        "    background: var(--bg-secondary);\n"
        "    border-bottom: 1px solid var(--border-color);\n"
        "    padding: 0 2rem;\n"
        "    overflow-x: auto;\n"
        "    white-space: nowrap;\n"
        "}\n"
        "\n"
        ".tabs::-webkit-scrollbar {\n"
        "    height: 4px;\n"
        "}\n"
        "\n"
        ".tabs::-webkit-scrollbar-track {\n"
        "    background: var(--bg-secondary);\n"
        "}\n"
        "\n"
        ".tabs::-webkit-scrollbar-thumb {\n"
        "    background: var(--border-color);\n"
        "    border-radius: 2px;\n"
        "}\n"
        "\n"
        ".tab {\n"
        "    background: none;\n"
        "    border: none;\n"
        "    color: var(--text-secondary);\n"
        "    padding: 1rem 1.5rem;\n"
        "    cursor: pointer;\n"
        "    border-bottom: 2px solid transparent;\n"
        "    transition: all 0.2s;\n"
        "    display: inline-flex;\n"
        "    align-items: center;\n"
        "    gap: 0.5rem;\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        ".tab svg {\n"
        "    width: 1.25rem;\n"
        "    height: 1.25rem;\n"
        "}\n"
        "\n"
        ".tab:hover {\n"
        "    color: var(--text-primary);\n"
        "    background: var(--bg-tertiary);\n"
        "}\n"
        "\n"
        ".tab.active {\n"
        "    color: var(--accent-primary);\n"
        "    border-bottom-color: var(--accent-primary);\n"
        "}\n"
        "\n"
        "/* Content Area */\n"
        ".content {\n"
        "    flex: 1;\n"
        "    padding: 2rem;\n"
        "    max-width: 1400px;\n"
        "    width: 100%;\n"
        "    margin: 0 auto;\n"
        "}\n"
        "\n"
        ".tab-content {\n"
        "    display: none;\n"
        "    animation: fadeIn 0.3s;\n"
        "}\n"
        "\n"
        ".tab-content.active {\n"
        "    display: block;\n"
        "}\n"
        "\n"
        "@keyframes fadeIn {\n"
        "    from { opacity: 0; transform: translateY(10px); }\n"
        "    to { opacity: 1; transform: translateY(0); }\n"
        "}\n"
        "\n"
        "/* Grid Layout */\n"
        ".grid {\n"
        "    display: grid;\n"
        "    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n"
        "    gap: 1.5rem;\n"
        "}\n"
        "\n"
        ".grid-2 {\n"
        "    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n"
        "}\n"
        "\n"
        "/* Cards */\n"
        ".card {\n"
        "    background: var(--bg-card);\n"
        "    border: 1px solid var(--border-color);\n"
        "    border-radius: 0.5rem;\n"
        "    padding: 1.5rem;\n"
        "    transition: transform 0.2s;\n"
        "}\n"
        "\n"
        ".card:hover {\n"
        "    transform: translateY(-2px);\n"
        "}\n"
        "\n"
        ".card.wide {\n"
        "    grid-column: 1 / -1;\n"
        "}\n"
        "\n"
        ".card h2 {\n"
        "    font-size: 1.25rem;\n"
        "    margin-bottom: 1rem;\n"
        "    color: var(--text-primary);\n"
        "}\n"
        "\n"
        ".card h3 {\n"
        "    font-size: 1rem;\n"
        "    margin-bottom: 0.75rem;\n"
        "    color: var(--text-secondary);\n"
        "}\n"
        "\n"
        ".card-header {\n"
        "    display: flex;\n"
        "    justify-content: space-between;\n"
        "    align-items: center;\n"
        "    margin-bottom: 1rem;\n"
        "    flex-wrap: wrap;\n"
        "    gap: 1rem;\n"
        "}\n"
        "\n"
        "/* Stats */\n"
        ".stat-row {\n"
        "    display: flex;\n"
        "    justify-content: space-between;\n"
        "    padding: 0.75rem 0;\n"
        "    border-bottom: 1px solid var(--border-color);\n"
        "}\n"
        "\n"
        ".stat-row:last-child {\n"
        "    border-bottom: none;\n"
        "}\n"
        "\n"
        ".stat-label {\n"
        "    color: var(--text-secondary);\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        ".stat-value {\n"
        "    color: var(--text-primary);\n"
        "    font-weight: 600;\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        ".proto-stats {\n"
        "    display: grid;\n"
        "    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n"
        "    gap: 1.5rem;\n"
        "}\n"
        "\n"
        ".proto-stat {\n"
        "    padding: 1rem;\n"
        "    background: var(--bg-tertiary);\n"
        "    border-radius: 0.375rem;\n"
        "}\n"
        "\n"
        "/* Forms */\n"
        ".form-group {\n"
        "    margin-bottom: 1.25rem;\n"
        "}\n"
        "\n"
        ".form-group label {\n"
        "    display: block;\n"
        "    margin-bottom: 0.5rem;\n"
        "    color: var(--text-secondary);\n"
        "    font-size: 0.875rem;\n"
        "    font-weight: 500;\n"
        "}\n"
        "\n"
        ".form-group input[type=\"text\"],\n"
        ".form-group input[type=\"password\"],\n"
        ".form-group input[type=\"number\"],\n"
        ".form-group select {\n"
        "    width: 100%;\n"
        "    padding: 0.75rem;\n"
        "    background: var(--bg-tertiary);\n"
        "    border: 1px solid var(--border-color);\n"
        "    border-radius: 0.375rem;\n"
        "    color: var(--text-primary);\n"
        "    font-size: 0.875rem;\n"
        "    transition: border-color 0.2s;\n"
        "}\n"
        "\n"
        ".form-group input[type=\"text\"]:focus,\n"
        ".form-group input[type=\"password\"]:focus,\n"
        ".form-group input[type=\"number\"]:focus,\n"
        ".form-group select:focus {\n"
        "    outline: none;\n"
        "    border-color: var(--accent-primary);\n"
        "}\n"
        "\n"
        ".form-group input[type=\"checkbox\"] {\n"
        "    margin-right: 0.5rem;\n"
        "}\n"
        "\n"
        ".form-group input[type=\"file\"] {\n"
        "    width: 100%;\n"
        "    padding: 0.75rem;\n"
        "    background: var(--bg-tertiary);\n"
        "    border: 1px solid var(--border-color);\n"
        "    border-radius: 0.375rem;\n"
        "    color: var(--text-primary);\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        ".help-text {\n"
        "    display: block;\n"
        "    margin-top: 0.375rem;\n"
        "    color: var(--text-muted);\n"
        "    font-size: 0.75rem;\n"
        "}\n"
        "\n"
        ".form-section {\n"
        "    margin-top: 1.5rem;\n"
        "    padding-top: 1.5rem;\n"
        "    border-top: 1px solid var(--border-color);\n"
        "}\n"
        "\n"
        ".form-actions {\n"
        "    display: flex;\n"
        "    gap: 0.75rem;\n"
        "    margin-top: 1.5rem;\n"
        "    flex-wrap: wrap;\n"
        "}\n"
        "\n"
        "/* Buttons */\n"
        ".btn {\n"
        "    padding: 0.75rem 1.5rem;\n"
        "    background: var(--bg-tertiary);\n"
        "    border: 1px solid var(--border-color);\n"
        "    border-radius: 0.375rem;\n"
        "    color: var(--text-primary);\n"
        "    font-size: 0.875rem;\n"
        "    font-weight: 500;\n"
        "    cursor: pointer;\n"
        "    transition: all 0.2s;\n"
        "    display: inline-flex;\n"
        "    align-items: center;\n"
        "    gap: 0.5rem;\n"
        "}\n"
        "\n"
        ".btn:hover {\n"
        "    background: var(--border-color);\n"
        "}\n"
        "\n"
        ".btn svg {\n"
        "    width: 1rem;\n"
        "    height: 1rem;\n"
        "}\n"
        "\n"
        ".btn-primary {\n"
        "    background: var(--accent-primary);\n"
        "    border-color: var(--accent-primary);\n"
        "}\n"
        "\n"
        ".btn-primary:hover {\n"
        "    background: var(--accent-hover);\n"
        "    border-color: var(--accent-hover);\n"
        "}\n"
        "\n"
        ".btn-success {\n"
        "    background: var(--success);\n"
        "    border-color: var(--success);\n"
        "}\n"
        "\n"
        ".btn-warning {\n"
        "    background: var(--warning);\n"
        "    border-color: var(--warning);\n"
        "    color: #000;\n"
        "}\n"
        "\n"
        ".btn-danger {\n"
        "    background: var(--danger);\n"
        "    border-color: var(--danger);\n"
        "}\n"
        "\n"
        ".action-buttons {\n"
        "    display: flex;\n"
        "    flex-direction: column;\n"
        "    gap: 0.75rem;\n"
        "}\n"
        "\n"
        "/* Table */\n"
        ".table-responsive {\n"
        "    overflow-x: auto;\n"
        "    margin-top: 1rem;\n"
        "}\n"
        "\n"
        ".data-table {\n"
        "    width: 100%;\n"
        "    border-collapse: collapse;\n"
        "}\n"
        "\n"
        ".data-table th,\n"
        ".data-table td {\n"
        "    padding: 0.75rem;\n"
        "    text-align: left;\n"
        "    border-bottom: 1px solid var(--border-color);\n"
        "}\n"
        "\n"
        ".data-table th {\n"
        "    background: var(--bg-tertiary);\n"
        "    color: var(--text-secondary);\n"
        "    font-weight: 600;\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        ".data-table td {\n"
        "    color: var(--text-primary);\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        ".data-table .no-data {\n"
        "    text-align: center;\n"
        "    color: var(--text-muted);\n"
        "    padding: 2rem;\n"
        "}\n"
        "\n"
        "/* Status Message */\n"
        ".status-message {\n"
        "    padding: 1rem;\n"
        "    background: var(--bg-tertiary);\n"
        "    border-radius: 0.375rem;\n"
        "    margin-bottom: 1rem;\n"
        "    color: var(--text-secondary);\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        "/* Alert */\n"
        ".alert {\n"
        "    padding: 1rem;\n"
        "    border-radius: 0.375rem;\n"
        "    margin-top: 1rem;\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        ".alert-warning {\n"
        "    background: rgba(245, 158, 11, 0.1);\n"
        "    border: 1px solid var(--warning);\n"
        "    color: var(--warning);\n"
        "}\n"
        "\n"
        "/* Progress Bar */\n"
        ".progress {\n"
        "    width: 100%;\n"
        "    height: 2.5rem;\n"
        "    background: var(--bg-tertiary);\n"
        "    border-radius: 0.375rem;\n"
        "    overflow: hidden;\n"
        "    position: relative;\n"
        "    margin: 1rem 0;\n"
        "}\n"
        "\n"
        ".progress-bar {\n"
        "    height: 100%;\n"
        "    background: var(--accent-primary);\n"
        "    transition: width 0.3s;\n"
        "    width: 0%;\n"
        "}\n"
        "\n"
        ".progress-text {\n"
        "    position: absolute;\n"
        "    top: 50%;\n"
        "    left: 50%;\n"
        "    transform: translate(-50%, -50%);\n"
        "    font-weight: 600;\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        "/* Toast Notifications */\n"
        ".toast-container {\n"
        "    position: fixed;\n"
        "    top: 1rem;\n"
        "    right: 1rem;\n"
        "    z-index: 1000;\n"
        "    display: flex;\n"
        "    flex-direction: column;\n"
        "    gap: 0.75rem;\n"
        "}\n"
        "\n"
        ".toast {\n"
        "    min-width: 300px;\n"
        "    padding: 1rem;\n"
        "    background: var(--bg-card);\n"
        "    border: 1px solid var(--border-color);\n"
        "    border-radius: 0.5rem;\n"
        "    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.3);\n"
        "    animation: slideIn 0.3s;\n"
        "}\n"
        "\n"
        "@keyframes slideIn {\n"
        "    from {\n"
        "        transform: translateX(400px);\n"
        "        opacity: 0;\n"
        "    }\n"
        "    to {\n"
        "        transform: translateX(0);\n"
        "        opacity: 1;\n"
        "    }\n"
        "}\n"
        "\n"
        ".toast.success {\n"
        "    border-left: 4px solid var(--success);\n"
        "}\n"
        "\n"
        ".toast.error {\n"
        "    border-left: 4px solid var(--danger);\n"
        "}\n"
        "\n"
        ".toast.warning {\n"
        "    border-left: 4px solid var(--warning);\n"
        "}\n"
        "\n"
        ".toast.info {\n"
        "    border-left: 4px solid var(--info);\n"
        "}\n"
        "\n"
        ".toast-header {\n"
        "    font-weight: 600;\n"
        "    margin-bottom: 0.25rem;\n"
        "}\n"
        "\n"
        ".toast-body {\n"
        "    font-size: 0.875rem;\n"
        "    color: var(--text-secondary);\n"
        "}\n"
        "\n"
        "/* Responsive */\n"
        "@media (max-width: 768px) {\n"
        "    .header {\n"
        "        padding: 1rem;\n"
        "    }\n"
        "\n"
        "    .header h1 {\n"
        "        font-size: 1.25rem;\n"
        "    }\n"
        "\n"
        "    .tabs {\n"
        "        padding: 0 0.5rem;\n"
        "    }\n"
        "\n"
        "    .tab {\n"
        "        padding: 0.75rem 1rem;\n"
        "        font-size: 0.8125rem;\n"
        "    }\n"
        "\n"
        "    .content {\n"
        "        padding: 1rem;\n"
        "    }\n"
        "\n"
        "    .grid {\n"
        "        grid-template-columns: 1fr;\n"
        "    }\n"
        "\n"
        "    .form-actions {\n"
        "        flex-direction: column;\n"
        "    }\n"
        "\n"
        "    .form-actions .btn {\n"
        "        width: 100%;\n"
        "        justify-content: center;\n"
        "    }\n"
        "\n"
        "    .toast-container {\n"
        "        left: 1rem;\n"
        "        right: 1rem;\n"
        "    }\n"
        "\n"
        "    .toast {\n"
        "        min-width: auto;\n"
        "        width: 100%;\n"
        "    }\n"
        "}\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"app\">\n"
        "        <!-- Header -->\n"
        "        <header class=\"header\">\n"
        "            <div class=\"header-content\">\n"
        "                <h1>\n"
        "                    <svg class=\"logo\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n"
        "                        <path d=\"M13 2L3 14h9l-1 8 10-12h-9l1-8z\"/>\n"
        "                    </svg>\n"
        "                    ESP-NODE-2RDM\n"
        "                </h1>\n"
        "                <div class=\"connection-status\">\n"
        "                    <span class=\"status-indicator\" id=\"connectionStatus\"></span>\n"
        "                    <span id=\"connectionText\">Connecting...</span>\n"
        "                </div>\n"
        "            </div>\n"
        "        </header>\n"
        "\n"
        "        <!-- Navigation Tabs -->\n"
        "        <nav class=\"tabs\">\n"
        "            <button class=\"tab active\" data-tab=\"dashboard\">\n"
        "                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n"
        "                    <rect x=\"3\" y=\"3\" width=\"7\" height=\"7\"/>\n"
        "                    <rect x=\"14\" y=\"3\" width=\"7\" height=\"7\"/>\n"
        "                    <rect x=\"14\" y=\"14\" width=\"7\" height=\"7\"/>\n"
        "                    <rect x=\"3\" y=\"14\" width=\"7\" height=\"7\"/>\n"
        "                </svg>\n"
        "                Dashboard\n"
        "            </button>\n"
        "            <button class=\"tab\" data-tab=\"network\">\n"
        "                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n"
        "                    <circle cx=\"12\" cy=\"12\" r=\"2\"/>\n"
        "                    <path d=\"M16.24 7.76a6 6 0 0 1 0 8.49m-8.48-.01a6 6 0 0 1 0-8.49m11.31-2.82a10 10 0 0 1 0 14.14m-14.14 0a10 10 0 0 1 0-14.14\"/>\n"
        "                </svg>\n"
        "                Network\n"
        "            </button>\n"
        "            <button class=\"tab\" data-tab=\"dmx\">\n"
        "                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n"
        "                    <path d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"/>\n"
        "                    <polyline points=\"14 2 14 8 20 8\"/>\n"
        "                    <line x1=\"16\" y1=\"13\" x2=\"8\" y2=\"13\"/>\n"
        "                    <line x1=\"16\" y1=\"17\" x2=\"8\" y2=\"17\"/>\n"
        "                    <polyline points=\"10 9 9 9 8 9\"/>\n"
        "                </svg>\n"
        "                DMX/RDM\n"
        "            </button>\n"
        "            <button class=\"tab\" data-tab=\"rdm\">\n"
        "                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n"
        "                    <path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"/>\n"
        "                    <polyline points=\"3.27 6.96 12 12.01 20.73 6.96\"/>\n"
        "                    <line x1=\"12\" y1=\"22.08\" x2=\"12\" y2=\"12\"/>\n"
        "                </svg>\n"
        "                RDM Discovery\n"
        "            </button>\n"
        "            <button class=\"tab\" data-tab=\"system\">\n"
        "                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n"
        "                    <circle cx=\"12\" cy=\"12\" r=\"3\"/>\n"
        "                    <path d=\"M12 1v6m0 6v6M5.64 5.64l4.24 4.24m4.24 4.24l4.24 4.24M1 12h6m6 0h6M5.64 18.36l4.24-4.24m4.24-4.24l4.24-4.24\"/>\n"
        "                </svg>\n"
        "                System\n"
        "            </button>\n"
        "        </nav>\n"
        "\n"
        "        <!-- Tab Content -->\n"
        "        <main class=\"content\">\n"
        "            <!-- Dashboard Tab -->\n"
        "            <div class=\"tab-content active\" id=\"dashboard\">\n"
        "                <div class=\"grid\">\n"
        "                    <!-- System Status Card -->\n"
        "                    <div class=\"card\">\n"
        "                        <h2>System Status</h2>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Uptime:</span>\n"
        "                            <span class=\"stat-value\" id=\"uptime\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Free RAM:</span>\n"
        "                            <span class=\"stat-value\" id=\"freeHeap\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Firmware:</span>\n"
        "                            <span class=\"stat-value\" id=\"firmware\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Hardware:</span>\n"
        "                            <span class=\"stat-value\" id=\"hardware\">--</span>\n"
        "                        </div>\n"
        "                    </div>\n"
        "\n"
        "                    <!-- Network Status Card -->\n"
        "                    <div class=\"card\">\n"
        "                        <h2>Network Status</h2>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Mode:</span>\n"
        "                            <span class=\"stat-value\" id=\"netMode\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">IP Address:</span>\n"
        "                            <span class=\"stat-value\" id=\"ipAddress\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Status:</span>\n"
        "                            <span class=\"stat-value\" id=\"netStatus\">--</span>\n"
        "                        </div>\n"
        "                    </div>\n"
        "\n"
        "                    <!-- Port 1 Status -->\n"
        "                    <div class=\"card\">\n"
        "                        <h2>Port 1 (DMX Out)</h2>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Mode:</span>\n"
        "                            <span class=\"stat-value\" id=\"port1Mode\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Universe:</span>\n"
        "                            <span class=\"stat-value\" id=\"port1Universe\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Frames Sent:</span>\n"
        "                            <span class=\"stat-value\" id=\"port1Frames\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Refresh Rate:</span>\n"
        "                            <span class=\"stat-value\" id=\"port1Rate\">-- Hz</span>\n"
        "                        </div>\n"
        "                        <button class=\"btn btn-warning\" onclick=\"app.blackoutPort(1)\">Blackout</button>\n"
        "                    </div>\n"
        "\n"
        "                    <!-- Port 2 Status -->\n"
        "                    <div class=\"card\">\n"
        "                        <h2>Port 2 (DMX Out)</h2>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Mode:</span>\n"
        "                            <span class=\"stat-value\" id=\"port2Mode\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Universe:</span>\n"
        "                            <span class=\"stat-value\" id=\"port2Universe\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Frames Sent:</span>\n"
        "                            <span class=\"stat-value\" id=\"port2Frames\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Refresh Rate:</span>\n"
        "                            <span class=\"stat-value\" id=\"port2Rate\">-- Hz</span>\n"
        "                        </div>\n"
        "                        <button class=\"btn btn-warning\" onclick=\"app.blackoutPort(2)\">Blackout</button>\n"
        "                    </div>\n"
        "\n"
        "                    <!-- Protocol Statistics -->\n"
        "                    <div class=\"card wide\">\n"
        "                        <h2>Protocol Statistics</h2>\n"
        "                        <div class=\"proto-stats\">\n"
        "                            <div class=\"proto-stat\">\n"
        "                                <h3>Art-Net</h3>\n"
        "                                <div class=\"stat-row\">\n"
        "                                    <span class=\"stat-label\">Total Packets:</span>\n"
        "                                    <span class=\"stat-value\" id=\"artnetPackets\">--</span>\n"
        "                                </div>\n"
        "                                <div class=\"stat-row\">\n"
        "                                    <span class=\"stat-label\">DMX Packets:</span>\n"
        "                                    <span class=\"stat-value\" id=\"artnetDmx\">--</span>\n"
        "                                </div>\n"
        "                            </div>\n"
        "                            <div class=\"proto-stat\">\n"
        "                                <h3>sACN</h3>\n"
        "                                <div class=\"stat-row\">\n"
        "                                    <span class=\"stat-label\">Total Packets:</span>\n"
        "                                    <span class=\"stat-value\" id=\"sacnPackets\">--</span>\n"
        "                                </div>\n"
        "                                <div class=\"stat-row\">\n"
        "                                    <span class=\"stat-label\">Data Packets:</span>\n"
        "                                    <span class=\"stat-value\" id=\"sacnData\">--</span>\n"
        "                                </div>\n"
        "                            </div>\n"
        "                        </div>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- Network Settings Tab -->\n"
        "            <div class=\"tab-content\" id=\"network\">\n"
        "                <div class=\"card\">\n"
        "                    <h2>Network Configuration</h2>\n"
        "                    <form id=\"networkForm\" onsubmit=\"return app.saveNetworkConfig(event)\">\n"
        "                        <div class=\"form-group\">\n"
        "                            <label>Network Mode</label>\n"
        "                            <select name=\"netMode\" id=\"netModeSelect\">\n"
        "                                <option value=\"sta\">Station (Client)</option>\n"
        "                                <option value=\"ap\">Access Point</option>\n"
        "                                <option value=\"eth\">Ethernet</option>\n"
        "                            </select>\n"
        "                        </div>\n"
        "\n"
        "                        <div class=\"form-section\" id=\"wifiSettings\">\n"
        "                            <h3>WiFi Settings</h3>\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>SSID</label>\n"
        "                                <input type=\"text\" name=\"wifi_ssid\" placeholder=\"Network name\">\n"
        "                            </div>\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Password</label>\n"
        "                                <input type=\"password\" name=\"wifi_password\" placeholder=\"Network password\">\n"
        "                            </div>\n"
        "                        </div>\n"
        "\n"
        "                        <div class=\"form-section\" id=\"ipSettings\">\n"
        "                            <h3>IP Configuration</h3>\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>\n"
        "                                    <input type=\"checkbox\" name=\"dhcp\" checked> Use DHCP\n"
        "                                </label>\n"
        "                            </div>\n"
        "                            <div class=\"static-ip\" style=\"display: none;\">\n"
        "                                <div class=\"form-group\">\n"
        "                                    <label>IP Address</label>\n"
        "                                    <input type=\"text\" name=\"static_ip\" placeholder=\"192.168.1.100\">\n"
        "                                </div>\n"
        "                                <div class=\"form-group\">\n"
        "                                    <label>Gateway</label>\n"
        "                                    <input type=\"text\" name=\"gateway\" placeholder=\"192.168.1.1\">\n"
        "                                </div>\n"
        "                                <div class=\"form-group\">\n"
        "                                    <label>Subnet Mask</label>\n"
        "                                    <input type=\"text\" name=\"netmask\" placeholder=\"255.255.255.0\">\n"
        "                                </div>\n"
        "                            </div>\n"
        "                        </div>\n"
        "\n"
        "                        <div class=\"form-actions\">\n"
        "                            <button type=\"submit\" class=\"btn btn-primary\">Save Configuration</button>\n"
        "                            <button type=\"button\" class=\"btn\" onclick=\"app.loadNetworkConfig()\">Reload</button>\n"
        "                        </div>\n"
        "                    </form>\n"
        "                </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- DMX/RDM Configuration Tab -->\n"
        "            <div class=\"tab-content\" id=\"dmx\">\n"
        "                <div class=\"grid\">\n"
        "                    <!-- Port 1 Configuration -->\n"
        "                    <div class=\"card\">\n"
        "                        <h2>Port 1 Configuration</h2>\n"
        "                        <form id=\"port1Form\" onsubmit=\"return app.savePortConfig(event, 1)\">\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Universe</label>\n"
        "                                <input type=\"number\" name=\"universe\" min=\"0\" max=\"32767\" value=\"0\">\n"
        "                            </div>\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Mode</label>\n"
        "                                <select name=\"mode\">\n"
        "                                    <option value=\"0\">Disabled</option>\n"
        "                                    <option value=\"1\" selected>DMX Output</option>\n"
        "                                    <option value=\"2\">DMX Input</option>\n"
        "                                    <option value=\"3\">RDM Master</option>\n"
        "                                    <option value=\"4\">RDM Responder</option>\n"
        "                                </select>\n"
        "                            </div>\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Priority (sACN)</label>\n"
        "                                <input type=\"number\" name=\"priority\" min=\"0\" max=\"200\" value=\"100\">\n"
        "                            </div>\n"
        "                            <div class=\"form-actions\">\n"
        "                                <button type=\"submit\" class=\"btn btn-primary\">Apply</button>\n"
        "                            </div>\n"
        "                        </form>\n"
        "                    </div>\n"
        "\n"
        "                    <!-- Port 2 Configuration -->\n"
        "                    <div class=\"card\">\n"
        "                        <h2>Port 2 Configuration</h2>\n"
        "                        <form id=\"port2Form\" onsubmit=\"return app.savePortConfig(event, 2)\">\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Universe</label>\n"
        "                                <input type=\"number\" name=\"universe\" min=\"0\" max=\"32767\" value=\"1\">\n"
        "                            </div>\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Mode</label>\n"
        "                                <select name=\"mode\">\n"
        "                                    <option value=\"0\">Disabled</option>\n"
        "                                    <option value=\"1\" selected>DMX Output</option>\n"
        "                                    <option value=\"2\">DMX Input</option>\n"
        "                                    <option value=\"3\">RDM Master</option>\n"
        "                                    <option value=\"4\">RDM Responder</option>\n"
        "                                </select>\n"
        "                            </div>\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Priority (sACN)</label>\n"
        "                                <input type=\"number\" name=\"priority\" min=\"0\" max=\"200\" value=\"100\">\n"
        "                            </div>\n"
        "                            <div class=\"form-actions\">\n"
        "                                <button type=\"submit\" class=\"btn btn-primary\">Apply</button>\n"
        "                            </div>\n"
        "                        </form>\n"
        "                    </div>\n"
        "\n"
        "                    <!-- Merge Engine Settings -->\n"
        "                    <div class=\"card wide\">\n"
        "                        <h2>Merge Engine Configuration</h2>\n"
        "                        <div class=\"grid grid-2\">\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Port 1 Merge Mode</label>\n"
        "                                <select id=\"port1MergeMode\" onchange=\"app.saveMergeMode(1, this.value)\">\n"
        "                                    <option value=\"0\">HTP (Highest Takes Precedence)</option>\n"
        "                                    <option value=\"1\">LTP (Lowest Takes Precedence)</option>\n"
        "                                    <option value=\"2\">LAST (Latest Source)</option>\n"
        "                                    <option value=\"3\">BACKUP (Primary + Failover)</option>\n"
        "                                    <option value=\"4\">DISABLE (No Merge)</option>\n"
        "                                </select>\n"
        "                                <small class=\"help-text\">How to merge multiple sources for Port 1</small>\n"
        "                            </div>\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Port 2 Merge Mode</label>\n"
        "                                <select id=\"port2MergeMode\" onchange=\"app.saveMergeMode(2, this.value)\">\n"
        "                                    <option value=\"0\">HTP (Highest Takes Precedence)</option>\n"
        "                                    <option value=\"1\">LTP (Lowest Takes Precedence)</option>\n"
        "                                    <option value=\"2\">LAST (Latest Source)</option>\n"
        "                                    <option value=\"3\">BACKUP (Primary + Failover)</option>\n"
        "                                    <option value=\"4\">DISABLE (No Merge)</option>\n"
        "                                </select>\n"
        "                                <small class=\"help-text\">How to merge multiple sources for Port 2</small>\n"
        "                            </div>\n"
        "                        </div>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- RDM Discovery Tab -->\n"
        "            <div class=\"tab-content\" id=\"rdm\">\n"
        "                <div class=\"card\">\n"
        "                    <div class=\"card-header\">\n"
        "                        <h2>RDM Device Discovery</h2>\n"
        "                        <button class=\"btn btn-primary\" onclick=\"app.startRDMDiscovery()\">\n"
        "                            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n"
        "                                <path d=\"M21.5 2v6h-6M2.5 22v-6h6M2 11.5a10 10 0 0 1 18.8-4.3M22 12.5a10 10 0 0 1-18.8 4.2\"/>\n"
        "                            </svg>\n"
        "                            Scan Devices\n"
        "                        </button>\n"
        "                    </div>\n"
        "                    \n"
        "                    <div id=\"rdmStatus\" class=\"status-message\">\n"
        "                        Click \"Scan Devices\" to discover RDM devices on the network\n"
        "                    </div>\n"
        "\n"
        "                    <div class=\"table-responsive\">\n"
        "                        <table class=\"data-table\">\n"
        "                            <thead>\n"
        "                                <tr>\n"
        "                                    <th>Port</th>\n"
        "                                    <th>UID</th>\n"
        "                                    <th>Device Label</th>\n"
        "                                    <th>DMX Address</th>\n"
        "                                    <th>Manufacturer</th>\n"
        "                                    <th>Model</th>\n"
        "                                </tr>\n"
        "                            </thead>\n"
        "                            <tbody id=\"rdmDevicesTable\">\n"
        "                                <tr>\n"
        "                                    <td colspan=\"6\" class=\"no-data\">No devices discovered</td>\n"
        "                                </tr>\n"
        "                            </tbody>\n"
        "                        </table>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- System Tab -->\n"
        "            <div class=\"tab-content\" id=\"system\">\n"
        "                <div class=\"grid\">\n"
        "                    <!-- System Information -->\n"
        "                    <div class=\"card\">\n"
        "                        <h2>System Information</h2>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Firmware Version:</span>\n"
        "                            <span class=\"stat-value\" id=\"sysFirmware\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Hardware:</span>\n"
        "                            <span class=\"stat-value\" id=\"sysHardware\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">IDF Version:</span>\n"
        "                            <span class=\"stat-value\" id=\"sysIDF\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Free Heap:</span>\n"
        "                            <span class=\"stat-value\" id=\"sysFreeHeap\">--</span>\n"
        "                        </div>\n"
        "                        <div class=\"stat-row\">\n"
        "                            <span class=\"stat-label\">Uptime:</span>\n"
        "                            <span class=\"stat-value\" id=\"sysUptime\">--</span>\n"
        "                        </div>\n"
        "                    </div>\n"
        "\n"
        "                    <!-- System Actions -->\n"
        "                    <div class=\"card\">\n"
        "                        <h2>System Actions</h2>\n"
        "                        <div class=\"action-buttons\">\n"
        "                            <button class=\"btn btn-warning\" onclick=\"app.rebootDevice()\">\n"
        "                                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n"
        "                                    <path d=\"M21.5 2v6h-6M2.5 22v-6h6M2 11.5a10 10 0 0 1 18.8-4.3M22 12.5a10 10 0 0 1-18.8 4.2\"/>\n"
        "                                </svg>\n"
        "                                Reboot Device\n"
        "                            </button>\n"
        "                            <button class=\"btn btn-danger\" onclick=\"app.factoryReset()\">\n"
        "                                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n"
        "                                    <polyline points=\"3 6 5 6 21 6\"/>\n"
        "                                    <path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\"/>\n"
        "                                </svg>\n"
        "                                Factory Reset\n"
        "                            </button>\n"
        "                        </div>\n"
        "                    </div>\n"
        "\n"
        "                    <!-- Firmware Update -->\n"
        "                    <div class=\"card wide\">\n"
        "                        <h2>Firmware Update (OTA)</h2>\n"
        "                        <form id=\"otaForm\" onsubmit=\"return app.uploadFirmware(event)\">\n"
        "                            <div class=\"form-group\">\n"
        "                                <label>Select Firmware File (.bin)</label>\n"
        "                                <input type=\"file\" name=\"firmware\" accept=\".bin\" id=\"firmwareFile\">\n"
        "                            </div>\n"
        "                            <div id=\"uploadProgress\" class=\"progress\" style=\"display: none;\">\n"
        "                                <div class=\"progress-bar\" id=\"uploadProgressBar\"></div>\n"
        "                                <span class=\"progress-text\" id=\"uploadProgressText\">0%</span>\n"
        "                            </div>\n"
        "                            <div class=\"form-actions\">\n"
        "                                <button type=\"submit\" class=\"btn btn-primary\">Upload Firmware</button>\n"
        "                            </div>\n"
        "                            <div class=\"alert alert-warning\">\n"
        "                                <strong>Warning:</strong> Do not power off the device during firmware update!\n"
        "                            </div>\n"
        "                        </form>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </div>\n"
        "        </main>\n"
        "\n"
        "        <!-- Toast Notifications -->\n"
        "        <div class=\"toast-container\" id=\"toastContainer\"></div>\n"
        "    </div>\n"
        "\n"
        "    <script src=\"main.js\"></script>\n"
        "</body>\n"
        "</html>\n"
        "";

static const char *js_main = 
    "/**\n"
        " * ESP-NODE-2RDM Web Application\n"
        " * Single Page Application for device management\n"
        " */\n"
        "\n"
        "const app = {\n"
        "    ws: null,\n"
        "    wsReconnectTimer: null,\n"
        "    updateInterval: null,\n"
        "    lastFrameCount: { port1: 0, port2: 0 },\n"
        "    lastFrameTime: Date.now(),\n"
        "    \n"
        "    /**\n"
        "     * Initialize application\n"
        "     */\n"
        "    init() {\n"
        "        console.log('Initializing ESP-NODE-2RDM Web UI...');\n"
        "        \n"
        "        // Setup tab navigation\n"
        "        this.setupTabs();\n"
        "        \n"
        "        // Setup DHCP checkbox handler\n"
        "        this.setupDHCPToggle();\n"
        "        \n"
        "        // Load initial data\n"
        "        this.loadSystemInfo();\n"
        "        this.loadConfig();\n"
        "        this.loadPortsStatus();\n"
        "        \n"
        "        // Setup periodic updates\n"
        "        this.updateInterval = setInterval(() => {\n"
        "            this.updateDashboard();\n"
        "        }, 2000);\n"
        "        \n"
        "        // Try to connect WebSocket\n"
        "        this.connectWebSocket();\n"
        "        \n"
        "        // Update connection status\n"
        "        this.updateConnectionStatus(true);\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Setup tab navigation\n"
        "     */\n"
        "    setupTabs() {\n"
        "        const tabs = document.querySelectorAll('.tab');\n"
        "        const tabContents = document.querySelectorAll('.tab-content');\n"
        "        \n"
        "        tabs.forEach(tab => {\n"
        "            tab.addEventListener('click', () => {\n"
        "                const targetTab = tab.dataset.tab;\n"
        "                \n"
        "                // Remove active class from all tabs\n"
        "                tabs.forEach(t => t.classList.remove('active'));\n"
        "                tabContents.forEach(tc => tc.classList.remove('active'));\n"
        "                \n"
        "                // Add active class to clicked tab\n"
        "                tab.classList.add('active');\n"
        "                document.getElementById(targetTab).classList.add('active');\n"
        "            });\n"
        "        });\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Setup DHCP checkbox toggle\n"
        "     */\n"
        "    setupDHCPToggle() {\n"
        "        const dhcpCheckbox = document.querySelector('input[name=\"dhcp\"]');\n"
        "        const staticIPDiv = document.querySelector('.static-ip');\n"
        "        \n"
        "        if (dhcpCheckbox) {\n"
        "            dhcpCheckbox.addEventListener('change', (e) => {\n"
        "                staticIPDiv.style.display = e.target.checked ? 'none' : 'block';\n"
        "            });\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Update connection status indicator\n"
        "     */\n"
        "    updateConnectionStatus(connected) {\n"
        "        const indicator = document.getElementById('connectionStatus');\n"
        "        const text = document.getElementById('connectionText');\n"
        "        \n"
        "        if (connected) {\n"
        "            indicator.classList.add('connected');\n"
        "            indicator.classList.remove('disconnected');\n"
        "            text.textContent = 'Connected';\n"
        "        } else {\n"
        "            indicator.classList.remove('connected');\n"
        "            indicator.classList.add('disconnected');\n"
        "            text.textContent = 'Offline';\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Connect to WebSocket\n"
        "     */\n"
        "    connectWebSocket() {\n"
        "        try {\n"
        "            const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
        "            const wsUrl = `${protocol}//${window.location.host}/ws`;\n"
        "            \n"
        "            this.ws = new WebSocket(wsUrl);\n"
        "            \n"
        "            this.ws.onopen = () => {\n"
        "                console.log('WebSocket connected');\n"
        "                this.showToast('WebSocket connected', 'success');\n"
        "                clearTimeout(this.wsReconnectTimer);\n"
        "            };\n"
        "            \n"
        "            this.ws.onmessage = (event) => {\n"
        "                try {\n"
        "                    const data = JSON.parse(event.data);\n"
        "                    this.handleWebSocketMessage(data);\n"
        "                } catch (e) {\n"
        "                    console.error('WebSocket message parse error:', e);\n"
        "                }\n"
        "            };\n"
        "            \n"
        "            this.ws.onerror = (error) => {\n"
        "                console.error('WebSocket error:', error);\n"
        "            };\n"
        "            \n"
        "            this.ws.onclose = () => {\n"
        "                console.log('WebSocket disconnected');\n"
        "                this.ws = null;\n"
        "                // Attempt reconnection after 5 seconds\n"
        "                this.wsReconnectTimer = setTimeout(() => {\n"
        "                    this.connectWebSocket();\n"
        "                }, 5000);\n"
        "            };\n"
        "        } catch (e) {\n"
        "            console.error('WebSocket connection error:', e);\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Handle WebSocket messages\n"
        "     */\n"
        "    handleWebSocketMessage(data) {\n"
        "        // Handle real-time updates from device\n"
        "        console.log('WebSocket data:', data);\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Make API request\n"
        "     */\n"
        "    async apiRequest(url, options = {}) {\n"
        "        try {\n"
        "            const response = await fetch(url, {\n"
        "                ...options,\n"
        "                headers: {\n"
        "                    'Content-Type': 'application/json',\n"
        "                    ...options.headers\n"
        "                }\n"
        "            });\n"
        "            \n"
        "            if (!response.ok) {\n"
        "                throw new Error(`HTTP ${response.status}: ${response.statusText}`);\n"
        "            }\n"
        "            \n"
        "            return await response.json();\n"
        "        } catch (error) {\n"
        "            console.error('API request failed:', error);\n"
        "            this.showToast(`Request failed: ${error.message}`, 'error');\n"
        "            throw error;\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Load system information\n"
        "     */\n"
        "    async loadSystemInfo() {\n"
        "        try {\n"
        "            const data = await this.apiRequest('/api/system/info');\n"
        "            \n"
        "            // Update system info fields\n"
        "            document.getElementById('sysFirmware').textContent = data.firmware_version || '--';\n"
        "            document.getElementById('sysHardware').textContent = data.hardware || '--';\n"
        "            document.getElementById('sysIDF').textContent = data.idf_version || '--';\n"
        "            document.getElementById('sysFreeHeap').textContent = this.formatBytes(data.free_heap);\n"
        "            document.getElementById('sysUptime').textContent = this.formatUptime(data.uptime_sec);\n"
        "            \n"
        "            // Also update dashboard\n"
        "            document.getElementById('firmware').textContent = data.firmware_version || '--';\n"
        "            document.getElementById('hardware').textContent = data.hardware || '--';\n"
        "            document.getElementById('freeHeap').textContent = this.formatBytes(data.free_heap);\n"
        "            document.getElementById('uptime').textContent = this.formatUptime(data.uptime_sec);\n"
        "            \n"
        "            this.updateConnectionStatus(true);\n"
        "        } catch (error) {\n"
        "            this.updateConnectionStatus(false);\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Load configuration\n"
        "     */\n"
        "    async loadConfig() {\n"
        "        try {\n"
        "            const data = await this.apiRequest('/api/config');\n"
        "            \n"
        "            // Update port configs\n"
        "            if (data.port1) {\n"
        "                const port1Form = document.getElementById('port1Form');\n"
        "                if (port1Form) {\n"
        "                    port1Form.universe.value = data.port1.universe_primary || 0;\n"
        "                    port1Form.mode.value = data.port1.mode || 1;\n"
        "                }\n"
        "                document.getElementById('port1MergeMode').value = data.port1.merge_mode || 0;\n"
        "            }\n"
        "            \n"
        "            if (data.port2) {\n"
        "                const port2Form = document.getElementById('port2Form');\n"
        "                if (port2Form) {\n"
        "                    port2Form.universe.value = data.port2.universe_primary || 1;\n"
        "                    port2Form.mode.value = data.port2.mode || 1;\n"
        "                }\n"
        "                document.getElementById('port2MergeMode').value = data.port2.merge_mode || 0;\n"
        "            }\n"
        "        } catch (error) {\n"
        "            console.error('Failed to load config:', error);\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Load ports status\n"
        "     */\n"
        "    async loadPortsStatus() {\n"
        "        try {\n"
        "            const data = await this.apiRequest('/api/ports/status');\n"
        "            \n"
        "            if (Array.isArray(data) && data.length >= 2) {\n"
        "                const port1 = data[0];\n"
        "                const port2 = data[1];\n"
        "                \n"
        "                // Update port 1\n"
        "                if (port1) {\n"
        "                    document.getElementById('port1Mode').textContent = this.getModeName(port1.mode);\n"
        "                    document.getElementById('port1Universe').textContent = port1.universe || '--';\n"
        "                    document.getElementById('port1Frames').textContent = port1.frames_sent || 0;\n"
        "                }\n"
        "                \n"
        "                // Update port 2\n"
        "                if (port2) {\n"
        "                    document.getElementById('port2Mode').textContent = this.getModeName(port2.mode);\n"
        "                    document.getElementById('port2Universe').textContent = port2.universe || '--';\n"
        "                    document.getElementById('port2Frames').textContent = port2.frames_sent || 0;\n"
        "                }\n"
        "            }\n"
        "        } catch (error) {\n"
        "            console.error('Failed to load ports status:', error);\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Update dashboard with latest data\n"
        "     */\n"
        "    async updateDashboard() {\n"
        "        try {\n"
        "            // Update system info\n"
        "            const sysInfo = await this.apiRequest('/api/system/info');\n"
        "            document.getElementById('freeHeap').textContent = this.formatBytes(sysInfo.free_heap);\n"
        "            document.getElementById('uptime').textContent = this.formatUptime(sysInfo.uptime_sec);\n"
        "            document.getElementById('sysFreeHeap').textContent = this.formatBytes(sysInfo.free_heap);\n"
        "            document.getElementById('sysUptime').textContent = this.formatUptime(sysInfo.uptime_sec);\n"
        "            \n"
        "            // Update network status\n"
        "            try {\n"
        "                const netStatus = await this.apiRequest('/api/network/status');\n"
        "                document.getElementById('netMode').textContent = netStatus.mode || 'Unknown';\n"
        "                document.getElementById('ipAddress').textContent = netStatus.ip || 'Not connected';\n"
        "                document.getElementById('netStatus').textContent = netStatus.connected ? 'Connected' : 'Disconnected';\n"
        "            } catch (e) {\n"
        "                // Network API might not be implemented\n"
        "                document.getElementById('netMode').textContent = 'N/A';\n"
        "                document.getElementById('ipAddress').textContent = window.location.hostname;\n"
        "                document.getElementById('netStatus').textContent = 'Connected';\n"
        "            }\n"
        "            \n"
        "            // Update protocol stats\n"
        "            const stats = await this.apiRequest('/api/system/stats');\n"
        "            \n"
        "            if (stats.artnet) {\n"
        "                document.getElementById('artnetPackets').textContent = stats.artnet.packets || 0;\n"
        "                document.getElementById('artnetDmx').textContent = stats.artnet.dmx_packets || 0;\n"
        "            }\n"
        "            \n"
        "            if (stats.sacn) {\n"
        "                document.getElementById('sacnPackets').textContent = stats.sacn.packets || 0;\n"
        "                document.getElementById('sacnData').textContent = stats.sacn.data_packets || 0;\n"
        "            }\n"
        "            \n"
        "            // Update ports status\n"
        "            const portsStatus = await this.apiRequest('/api/ports/status');\n"
        "            \n"
        "            if (Array.isArray(portsStatus) && portsStatus.length >= 2) {\n"
        "                const port1 = portsStatus[0];\n"
        "                const port2 = portsStatus[1];\n"
        "                \n"
        "                // Calculate refresh rate\n"
        "                const now = Date.now();\n"
        "                const timeDelta = (now - this.lastFrameTime) / 1000;\n"
        "                \n"
        "                if (port1) {\n"
        "                    const framesDelta1 = port1.frames_sent - this.lastFrameCount.port1;\n"
        "                    const rate1 = timeDelta > 0 ? (framesDelta1 / timeDelta).toFixed(1) : '0.0';\n"
        "                    \n"
        "                    document.getElementById('port1Frames').textContent = port1.frames_sent || 0;\n"
        "                    document.getElementById('port1Rate').textContent = rate1 + ' Hz';\n"
        "                    this.lastFrameCount.port1 = port1.frames_sent;\n"
        "                }\n"
        "                \n"
        "                if (port2) {\n"
        "                    const framesDelta2 = port2.frames_sent - this.lastFrameCount.port2;\n"
        "                    const rate2 = timeDelta > 0 ? (framesDelta2 / timeDelta).toFixed(1) : '0.0';\n"
        "                    \n"
        "                    document.getElementById('port2Frames').textContent = port2.frames_sent || 0;\n"
        "                    document.getElementById('port2Rate').textContent = rate2 + ' Hz';\n"
        "                    this.lastFrameCount.port2 = port2.frames_sent;\n"
        "                }\n"
        "                \n"
        "                this.lastFrameTime = now;\n"
        "            }\n"
        "            \n"
        "            this.updateConnectionStatus(true);\n"
        "        } catch (error) {\n"
        "            this.updateConnectionStatus(false);\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Save network configuration\n"
        "     */\n"
        "    async saveNetworkConfig(event) {\n"
        "        event.preventDefault();\n"
        "        \n"
        "        const formData = new FormData(event.target);\n"
        "        const config = {\n"
        "            network: {\n"
        "                mode: formData.get('netMode'),\n"
        "                wifi_ssid: formData.get('wifi_ssid'),\n"
        "                wifi_password: formData.get('wifi_password'),\n"
        "                use_dhcp: formData.get('dhcp') === 'on',\n"
        "                static_ip: formData.get('static_ip'),\n"
        "                gateway: formData.get('gateway'),\n"
        "                netmask: formData.get('netmask')\n"
        "            }\n"
        "        };\n"
        "        \n"
        "        try {\n"
        "            await this.apiRequest('/api/config', {\n"
        "                method: 'POST',\n"
        "                body: JSON.stringify(config)\n"
        "            });\n"
        "            \n"
        "            this.showToast('Network configuration saved successfully', 'success');\n"
        "        } catch (error) {\n"
        "            this.showToast('Failed to save network configuration', 'error');\n"
        "        }\n"
        "        \n"
        "        return false;\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Load network configuration\n"
        "     */\n"
        "    async loadNetworkConfig() {\n"
        "        try {\n"
        "            const config = await this.apiRequest('/api/config');\n"
        "            \n"
        "            if (config.network) {\n"
        "                const form = document.getElementById('networkForm');\n"
        "                if (form) {\n"
        "                    form.netMode.value = config.network.mode || 'sta';\n"
        "                    form.wifi_ssid.value = config.network.wifi_ssid || '';\n"
        "                    form.wifi_password.value = '';  // Don't populate password\n"
        "                    form.dhcp.checked = config.network.use_dhcp !== false;\n"
        "                    form.static_ip.value = config.network.static_ip || '';\n"
        "                    form.gateway.value = config.network.gateway || '';\n"
        "                    form.netmask.value = config.network.netmask || '';\n"
        "                    \n"
        "                    // Update static IP visibility\n"
        "                    document.querySelector('.static-ip').style.display = \n"
        "                        form.dhcp.checked ? 'none' : 'block';\n"
        "                }\n"
        "            }\n"
        "            \n"
        "            this.showToast('Network configuration loaded', 'info');\n"
        "        } catch (error) {\n"
        "            this.showToast('Failed to load network configuration', 'error');\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Save port configuration\n"
        "     */\n"
        "    async savePortConfig(event, port) {\n"
        "        event.preventDefault();\n"
        "        \n"
        "        const formData = new FormData(event.target);\n"
        "        const config = {\n"
        "            [`port${port}`]: {\n"
        "                mode: parseInt(formData.get('mode')),\n"
        "                universe_primary: parseInt(formData.get('universe')),\n"
        "                priority: parseInt(formData.get('priority'))\n"
        "            }\n"
        "        };\n"
        "        \n"
        "        try {\n"
        "            await this.apiRequest('/api/config', {\n"
        "                method: 'POST',\n"
        "                body: JSON.stringify(config)\n"
        "            });\n"
        "            \n"
        "            this.showToast(`Port ${port} configuration saved`, 'success');\n"
        "            this.loadPortsStatus();  // Refresh port status\n"
        "        } catch (error) {\n"
        "            this.showToast(`Failed to save Port ${port} configuration`, 'error');\n"
        "        }\n"
        "        \n"
        "        return false;\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Save merge mode\n"
        "     */\n"
        "    async saveMergeMode(port, mode) {\n"
        "        const config = {\n"
        "            [`port${port}`]: {\n"
        "                merge_mode: parseInt(mode)\n"
        "            }\n"
        "        };\n"
        "        \n"
        "        try {\n"
        "            await this.apiRequest('/api/config', {\n"
        "                method: 'POST',\n"
        "                body: JSON.stringify(config)\n"
        "            });\n"
        "            \n"
        "            this.showToast(`Port ${port} merge mode updated`, 'success');\n"
        "        } catch (error) {\n"
        "            this.showToast(`Failed to update merge mode`, 'error');\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Blackout port\n"
        "     */\n"
        "    async blackoutPort(port) {\n"
        "        try {\n"
        "            await this.apiRequest(`/api/ports/${port}/blackout`, {\n"
        "                method: 'POST'\n"
        "            });\n"
        "            \n"
        "            this.showToast(`Port ${port} blackout activated`, 'warning');\n"
        "        } catch (error) {\n"
        "            this.showToast(`Failed to blackout Port ${port}`, 'error');\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Start RDM discovery\n"
        "     */\n"
        "    async startRDMDiscovery() {\n"
        "        const statusDiv = document.getElementById('rdmStatus');\n"
        "        const tableBody = document.getElementById('rdmDevicesTable');\n"
        "        \n"
        "        statusDiv.textContent = 'Scanning for RDM devices...';\n"
        "        statusDiv.style.color = 'var(--info)';\n"
        "        \n"
        "        try {\n"
        "            // This is a placeholder - actual RDM discovery API needs to be implemented\n"
        "            const devices = await this.apiRequest('/api/rdm/discover', {\n"
        "                method: 'POST'\n"
        "            });\n"
        "            \n"
        "            if (devices && devices.length > 0) {\n"
        "                statusDiv.textContent = `Found ${devices.length} device(s)`;\n"
        "                statusDiv.style.color = 'var(--success)';\n"
        "                \n"
        "                // Populate table\n"
        "                tableBody.innerHTML = devices.map(device => `\n"
        "                    <tr>\n"
        "                        <td>${device.port}</td>\n"
        "                        <td>${device.uid}</td>\n"
        "                        <td>${device.label}</td>\n"
        "                        <td>${device.dmx_address}</td>\n"
        "                        <td>${device.manufacturer}</td>\n"
        "                        <td>${device.model}</td>\n"
        "                    </tr>\n"
        "                `).join('');\n"
        "            } else {\n"
        "                statusDiv.textContent = 'No RDM devices found';\n"
        "                statusDiv.style.color = 'var(--text-muted)';\n"
        "                tableBody.innerHTML = '<tr><td colspan=\"6\" class=\"no-data\">No devices discovered</td></tr>';\n"
        "            }\n"
        "        } catch (error) {\n"
        "            statusDiv.textContent = 'RDM discovery failed or not yet implemented';\n"
        "            statusDiv.style.color = 'var(--danger)';\n"
        "            this.showToast('RDM discovery is not yet implemented', 'warning');\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Reboot device\n"
        "     */\n"
        "    async rebootDevice() {\n"
        "        if (!confirm('Are you sure you want to reboot the device?')) {\n"
        "            return;\n"
        "        }\n"
        "        \n"
        "        try {\n"
        "            await this.apiRequest('/api/system/restart', {\n"
        "                method: 'POST'\n"
        "            });\n"
        "            \n"
        "            this.showToast('Device is rebooting...', 'info');\n"
        "            \n"
        "            // Show countdown\n"
        "            let countdown = 10;\n"
        "            const countdownToast = setInterval(() => {\n"
        "                countdown--;\n"
        "                if (countdown <= 0) {\n"
        "                    clearInterval(countdownToast);\n"
        "                    window.location.reload();\n"
        "                } else {\n"
        "                    this.showToast(`Reconnecting in ${countdown} seconds...`, 'info');\n"
        "                }\n"
        "            }, 1000);\n"
        "        } catch (error) {\n"
        "            this.showToast('Failed to reboot device', 'error');\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Factory reset\n"
        "     */\n"
        "    async factoryReset() {\n"
        "        if (!confirm('Are you sure you want to factory reset? All settings will be lost!')) {\n"
        "            return;\n"
        "        }\n"
        "        \n"
        "        if (!confirm('This action cannot be undone. Continue?')) {\n"
        "            return;\n"
        "        }\n"
        "        \n"
        "        try {\n"
        "            await this.apiRequest('/api/system/factory-reset', {\n"
        "                method: 'POST'\n"
        "            });\n"
        "            \n"
        "            this.showToast('Factory reset initiated', 'warning');\n"
        "        } catch (error) {\n"
        "            this.showToast('Factory reset not yet implemented', 'warning');\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Upload firmware\n"
        "     */\n"
        "    async uploadFirmware(event) {\n"
        "        event.preventDefault();\n"
        "        \n"
        "        const fileInput = document.getElementById('firmwareFile');\n"
        "        const file = fileInput.files[0];\n"
        "        \n"
        "        if (!file) {\n"
        "            this.showToast('Please select a firmware file', 'error');\n"
        "            return false;\n"
        "        }\n"
        "        \n"
        "        if (!file.name.endsWith('.bin')) {\n"
        "            this.showToast('Invalid file type. Please select a .bin file', 'error');\n"
        "            return false;\n"
        "        }\n"
        "        \n"
        "        const progress = document.getElementById('uploadProgress');\n"
        "        const progressBar = document.getElementById('uploadProgressBar');\n"
        "        const progressText = document.getElementById('uploadProgressText');\n"
        "        \n"
        "        progress.style.display = 'block';\n"
        "        progressBar.style.width = '0%';\n"
        "        progressText.textContent = '0%';\n"
        "        \n"
        "        try {\n"
        "            // Simulate upload progress (replace with actual OTA upload)\n"
        "            for (let i = 0; i <= 100; i += 10) {\n"
        "                await new Promise(resolve => setTimeout(resolve, 500));\n"
        "                progressBar.style.width = i + '%';\n"
        "                progressText.textContent = i + '%';\n"
        "            }\n"
        "            \n"
        "            this.showToast('Firmware upload not yet implemented', 'warning');\n"
        "            progress.style.display = 'none';\n"
        "        } catch (error) {\n"
        "            this.showToast('Firmware upload failed', 'error');\n"
        "            progress.style.display = 'none';\n"
        "        }\n"
        "        \n"
        "        return false;\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Show toast notification\n"
        "     */\n"
        "    showToast(message, type = 'info') {\n"
        "        const container = document.getElementById('toastContainer');\n"
        "        const toast = document.createElement('div');\n"
        "        toast.className = `toast ${type}`;\n"
        "        \n"
        "        const header = document.createElement('div');\n"
        "        header.className = 'toast-header';\n"
        "        header.textContent = type.charAt(0).toUpperCase() + type.slice(1);\n"
        "        \n"
        "        const body = document.createElement('div');\n"
        "        body.className = 'toast-body';\n"
        "        body.textContent = message;\n"
        "        \n"
        "        toast.appendChild(header);\n"
        "        toast.appendChild(body);\n"
        "        container.appendChild(toast);\n"
        "        \n"
        "        // Auto remove after 5 seconds\n"
        "        setTimeout(() => {\n"
        "            toast.style.opacity = '0';\n"
        "            setTimeout(() => {\n"
        "                container.removeChild(toast);\n"
        "            }, 300);\n"
        "        }, 5000);\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Format bytes to human readable\n"
        "     */\n"
        "    formatBytes(bytes) {\n"
        "        if (!bytes) return '--';\n"
        "        const sizes = ['B', 'KB', 'MB', 'GB'];\n"
        "        const i = Math.floor(Math.log(bytes) / Math.log(1024));\n"
        "        return Math.round(bytes / Math.pow(1024, i) * 100) / 100 + ' ' + sizes[i];\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Format uptime to human readable\n"
        "     */\n"
        "    formatUptime(seconds) {\n"
        "        if (!seconds) return '--';\n"
        "        const days = Math.floor(seconds / 86400);\n"
        "        const hours = Math.floor((seconds % 86400) / 3600);\n"
        "        const minutes = Math.floor((seconds % 3600) / 60);\n"
        "        const secs = seconds % 60;\n"
        "        \n"
        "        if (days > 0) {\n"
        "            return `${days}d ${hours}h ${minutes}m`;\n"
        "        } else if (hours > 0) {\n"
        "            return `${hours}h ${minutes}m ${secs}s`;\n"
        "        } else if (minutes > 0) {\n"
        "            return `${minutes}m ${secs}s`;\n"
        "        } else {\n"
        "            return `${secs}s`;\n"
        "        }\n"
        "    },\n"
        "    \n"
        "    /**\n"
        "     * Get mode name from mode value\n"
        "     */\n"
        "    getModeName(mode) {\n"
        "        const modes = {\n"
        "            0: 'Disabled',\n"
        "            1: 'DMX Output',\n"
        "            2: 'DMX Input',\n"
        "            3: 'RDM Master',\n"
        "            4: 'RDM Responder'\n"
        "        };\n"
        "        return modes[mode] || 'Unknown';\n"
        "    }\n"
        "};\n"
        "\n"
        "// Initialize app when DOM is loaded\n"
        "if (document.readyState === 'loading') {\n"
        "    document.addEventListener('DOMContentLoaded', () => app.init());\n"
        "} else {\n"
        "    app.init();\n"
        "}\n"
        "\n"
        "// Make app globally accessible for onclick handlers\n"
        "window.app = app;\n"
        "";

